/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class MatrixJNI */

#ifndef _Included_MatrixJNI
#define _Included_MatrixJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     MatrixJNI
 * Method:    cat
 * Signature: ([Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_MatrixJNI_cat
  (JNIEnv *, jobject, jobjectArray, jstring);

/*
 * Class:     MatrixJNI
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_MatrixJNI_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
